export DESIGN_NAME = gcd
export PLATFORM = sky130hd

export VERILOG_FILES = $(DESIGN_HOME)/src/$(DESIGN_NICKNAME)/gcd.v
export SDC_FILE = $(DESIGN_HOME)/$(PLATFORM)/$(DESIGN_NICKNAME)/constraint.sdc

export ADDER_MAP_FILE :=
export CORE_UTILIZATION = 38
export TNS_END_PERCENT = 100
export SWAP_ARITH_OPERATORS = 0
export OPENROAD_HIERARCHICAL = 1
